### PR TITLE
Icons Redesign

### PR DESCRIPTION
**Pull request by Fatih20**
The previous icons did not comply by the [eOS HIG](https://elementary.io/docs/human-interface-guidelines#color) regarding the use of color. It should be red because red indicates "shutting down" or "stopping" as mentioned in the HIG. It also doesn't comply with the implementation of pictogram. It should be either extruded or inset.

### CODE REVIEW

**Comment by bcedu** [comment]
@Fatih20 Thanks for the effort but I don't know if i'm ok with the new design. 
The original icon is based in the icon from the shutdown dialog of elementaryOS:

Captura de pantalla del 2019-08-07 19 04 29


Maybe we could change the color of the "continue" button that is used to start the shutdown:

Captura de pantalla del 2019-08-07 19 27 01


It is done with a little coding:

```
diff --git a/data/resources/com.github.bcedu.shutdownscheduler.css b/data/resources/com.github.bcedu.shutdownscheduler.css
index 546f62d..1bb1a1e 100644
--- a/data/resources/com.github.bcedu.shutdownscheduler.css
+++ b/data/resources/com.github.bcedu.shutdownscheduler.css
@@ -37,3 +37,8 @@ conf_btn_entry, .conf_btn_entry{
 }
 conf_btn_types, .conf_btn_types{}
 
+redtimebutton, .redbutton {
+    background-color: #f6474f;
+    color: white;
+    border-color: #f6474f;
+}
diff --git a/src/Views/View1.vala b/src/Views/View1.vala
index b21077b..722644d 100644
--- a/src/Views/View1.vala
+++ b/src/Views/View1.vala
@@ -47,6 +47,7 @@ namespace App.Views {
         private Gtk.Box get_continue_button() {
             Gtk.Box box = new Gtk.Box(Gtk.Orientation.HORIZONTAL, 0);
             this.continue_button = new Button.with_label(_("Continue"));
+            this.continue_button.get_style_context().add_class ("redbutton");
             box.pack_start (this.continue_button, true, true, 10);
             return box;
         }
```

**Comment by Fatih20** [comment]
If your issue is the color I can fix it real quick.

**Comment by Fatih20** [comment]
If your issue is the color I can fix it real quick.

**Comment by Fatih20** [comment]
My main issue with your previous icon is that the files were png. That's just not okay.

**Comment by Fatih20** [comment]
If you want to base yourself on elementary OS, IMO, you should follow the clearly defined guidelines. In the palette apps based by Cassidy James, it is explicitly mentioned to use red for shutdown.

**Comment by Fatih20** [comment]
Also, I'm a designer. I don't give a damn about the code.

**Comment by bcedu** [comment]
> My main issue with your previous icon is that the files were png. That's just not okay.


I think that they where SVG, not PNG. And I like the current color, or at least, I don't like it in red (if you have any other sugestion it is wellcome :smile: )

**Comment by bcedu** [comment]
> Also, I'm a designer. I don't give a damn about the code.

ok... obviously I had no clue (how could I?)

**Comment by Fatih20** [comment]
You proceed to show me some code regarding Gtk that I can't read. But red IS the color for shutdown. As mentioned in the HIG, every color has a connotation. What's your argument for not using red?

**Comment by bcedu** [comment]
Ok, this is the **current icon** for the shutdown action from elementary OS:

shutdownlogo_eOS

Does it have red color? NO
Does it look familiar to you? YES, it's like the original ShutdownScheduler icon because I inspired in the official logo from elementary OS

That IS the reason because of I don't want a red icon.

This is my argument.

**Comment by Fatih20** [comment]
Problem is, that icon isn't the same color. Furthemore, the shutdown icon retain the shutdown meaning because the shape of the white bars at the middle is the same as a shutdown icon despite not being colored red. Your icon on the other hand isn't shaped like a shutdown icon and so, unlike the eOS shutdown icon, your icon doesn't retain the meaning of shutdown, only time because the bars in the middle is shaped like a clock, not a shutdown icon. It could be argued that a user would underatand overtime that the icon is a play on the original shutdown icon. However, an icon SHOULD retain basic meaning even when the user isn't thinking straight.

**Comment by bcedu** [comment]
Okey, what about red but mantaining the bars in white?

Something like this (but well done, because this has been made with gimp in 3 secons):

Captura de pantalla del 2019-08-22 01 08 23

**Comment by Fatih20** [comment]
I'll get on it.

**Pull request merged**
