### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by NathanBnm**
Hi! As I already made it in the PR that you previously closed, I bring the translations back.

I separated main translations from the appdata and desktop translations to make it easier to maintain. I also added other language files.

Finally I added French translations :smile: !

**This PR is ready for review**

### CODE REVIEW

**Comment by bcedu** [comment]
@NathanBnm After merging the PR https://github.com/bcedu/ShutdownScheduler/pull/30 and https://github.com/bcedu/ShutdownScheduler/pull/29 (and all other merged PR) I think you will have to refresh the translations. I will wait to merge this PR untill all others are merged

**Comment by NathanBnm** [comment]
Okay great, I'll check that

**Comment by NathanBnm** [comment]
I will be able to update translations once you'll have merged #24, #29 and #30. Just notify me! :+1:

**Comment by bcedu** [comment]
@NathanBnm I've merged all PR. You will need to update your branch with master.

**Comment by NathanBnm** [comment]
> @NathanBnm I've merged all PR. You will need to update your branch with master.

Great! I'll update translations asap so you can merge them soon :smile:

**Comment by NathanBnm** [comment]
@bcedu everything should be good now!

**Comment by bcedu** [comment]
@NathanBnm Why did you added all the po files (more than 300)? I think we should only add the translated ones.

**Comment by NathanBnm** [comment]
As you want, It depends of the developers. Adding all of them by default makes sure that people are respecting the file format. But I can remove the empty ones if you prefer.

**Pull request merged**
